In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import requests

In [14]:
data = pd.read_csv("CollegeScoreData/MERGED2021_22_PP.csv")
data.head()

/var/folders/35/13d00tc92bb7m81x0w1lfh5r0000gn/T/ipykernel_5598/3417971657.py:1: DtypeWarning: Columns (9,1725,1726,1727,1728,1729,1743,1815,1816,1817,1818,1823,1824,1830,1831,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1909,1910,1911,1912,1913,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1983,1984,2403,2404,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,3215,3231) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("CollegeScoreData/MERGED2021_22_PP.csv")

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOPELL_FIRSTTIME,OMENRUP_NOPELL_FIRSTTIME,OMENRYP_NOPELL_NOTFIRSTTIME,OMENRAP_NOPELL_NOTFIRSTTIME,OMAWDP8_NOPELL_NOTFIRSTTIME,OMENRUP_NOPELL_NOTFIRSTTIME,OMACHT8_NOPELL_ALL,OMACHT8_NOPELL_FIRSTTIME,OMACHT8_NOPELL_NOTFIRSTTIME,ADDR
0,100654,100200.0,1002.0,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www.aamu.edu/admissions-aid/tuition-fees/net-p...,...,0.3187,0.2709,0.0128,0.2949,0.4744,0.2179,329.0,251.0,78.0,4900 Meridian Street
1,100663,105200.0,1052.0,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,https://www.uab.edu/,https://tcc.ruffalonl.com/University of Alabam...,...,0.6937,0.0660,0.0111,0.2636,0.5136,0.2117,2358.0,1182.0,1176.0,Administration Bldg Suite 1070
2,100690,2503400.0,25034.0,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,https://www.amridgeuniversity.edu/,https://www2.amridgeuniversity.edu:9091/,...,0.0000,0.5000,0.0000,0.3333,0.4583,0.2083,26.0,2.0,24.0,1200 Taylor Rd
3,100706,105500.0,1055.0,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu/,finaid.uah.edu/,...,0.6471,0.0941,0.0082,0.2647,0.5948,0.1324,1122.0,510.0,612.0,301 Sparkman Dr
4,100724,100500.0,1005.0,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu/,www.alasu.edu/cost-aid/tuition-costs/net-price...,...,0.4381,0.2167,0.0000,0.1444,0.3667,0.4889,510.0,420.0,90.0,915 S Jackson Street

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6543 entries, 0 to 6542
Columns: 3232 entries, UNITID to ADDR
dtypes: float64(2693), int64(13), object(526)
memory usage: 161.3+ MB

In [6]:
data.describe()

,UNITID,OPEID,OPEID6,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,...,OMENRAP_NOPELL_FIRSTTIME,OMAWDP8_NOPELL_FIRSTTIME,OMENRUP_NOPELL_FIRSTTIME,OMENRYP_NOPELL_NOTFIRSTTIME,OMENRAP_NOPELL_NOTFIRSTTIME,OMAWDP8_NOPELL_NOTFIRSTTIME,OMENRUP_NOPELL_NOTFIRSTTIME,OMACHT8_NOPELL_ALL,OMACHT8_NOPELL_FIRSTTIME,OMACHT8_NOPELL_NOTFIRSTTIME
count,6.543000e+03,6.523000e+03,6523.000000,0.0,6543.000000,6543.000000,6543.000000,6543.000000,6543.000000,6543.000000,...,3513.000000,3513.000000,3513.000000,3519.000000,3519.000000,3519.000000,3519.000000,3649.000000,3649.000000,3649.000000
mean,2.346034e+06,1.748939e+06,17014.133221,NaN,0.007030,0.794437,3.151001,1.831729,2.235825,2.066025,...,0.204068,0.494559,0.293468,0.006987,0.192840,0.531300,0.268874,1307.443135,562.665388,744.777747
std,8.159248e+06,2.152323e+06,15181.014987,NaN,0.083559,0.404143,6.916664,1.082061,1.376703,0.833739,...,0.159683,0.240829,0.225290,0.029392,0.170384,0.235001,0.193989,2956.225321,935.277078,2372.852213
min,1.006540e+05,1.002000e+05,1002.000000,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.741315e+05,3.080505e+05,3072.500000,NaN,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.074100,0.303600,0.096400,0.000000,0.035700,0.345500,0.131250,115.000000,48.000000,34.000000
50%,2.293370e+05,1.031904e+06,10198.000000,NaN,0.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,0.206300,0.500000,0.265100,0.000000,0.175800,0.547600,0.238500,375.000000,215.000000,124.000000
75%,4.572395e+05,3.083350e+06,30780.000000,NaN,0.000000,1.000000,2.000000,3.000000,4.000000,3.000000,...,0.288700,0.681800,0.444400,0.008500,0.294100,0.705900,0.363600,1119.000000,632.000000,424.000000
max,4.966450e+07,8.209882e+07,42991.000000,NaN,1.000000,1.000000,56.000000,4.000000,4.000000,3.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,38456.000000,12761.000000,32936.000000

In [12]:
data_dict = pd.read_excel("CollegeScorecardDataDictionary.xlsx")
data_dict.head()

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (__init__.py, line 1187)